"""add freight bill candidate matches

Revision ID: 285912061f20
Revises: 9386c6fa9b1f
Create Date: 2026-04-23 13:26:32.917642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285912061f20'
down_revision: Union[str, None] = '9386c6fa9b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freight_bill_candidate_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('freight_bill_id', sa.String(length=100), nullable=False),
    sa.Column('candidate_type', sa.String(length=50), nullable=False),
    sa.Column('candidate_id', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('match_reasons', sa.JSON(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['freight_bill_id'], ['freight_bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_bill_candidate_matches_candidate_id'), 'freight_bill_candidate_matches', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_freight_bill_candidate_matches_candidate_type'), 'freight_bill_candidate_matches', ['candidate_type'], unique=False)
    op.create_index(op.f('ix_freight_bill_candidate_matches_freight_bill_id'), 'freight_bill_candidate_matches', ['freight_bill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_freight_bill_candidate_matches_freight_bill_id'), table_name='freight_bill_candidate_matches')
    op.drop_index(op.f('ix_freight_bill_candidate_matches_candidate_type'), table_name='freight_bill_candidate_matches')
    op.drop_index(op.f('ix_freight_bill_candidate_matches_candidate_id'), table_name='freight_bill_candidate_matches')
    op.drop_table('freight_bill_candidate_matches')
    # ### end Alembic commands ###
