"""add freight bill decisions

Revision ID: 7ae7c1214bb0
Revises: b7b20eba6360
Create Date: 2026-04-23 19:22:23.457504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae7c1214bb0'
down_revision: Union[str, None] = 'b7b20eba6360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freight_bill_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('freight_bill_id', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('decision_source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['freight_bill_id'], ['freight_bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_bill_decisions_freight_bill_id'), 'freight_bill_decisions', ['freight_bill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_freight_bill_decisions_freight_bill_id'), table_name='freight_bill_decisions')
    op.drop_table('freight_bill_decisions')
    # ### end Alembic commands ###
