"""add freight bill validations

Revision ID: 855bfd97d9b3
Revises: 285912061f20
Create Date: 2026-04-23 13:48:13.344583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '855bfd97d9b3'
down_revision: Union[str, None] = '285912061f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freight_bill_validations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('freight_bill_id', sa.String(length=100), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('rule_result', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['freight_bill_id'], ['freight_bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_bill_validations_freight_bill_id'), 'freight_bill_validations', ['freight_bill_id'], unique=False)
    op.create_index(op.f('ix_freight_bill_validations_rule_name'), 'freight_bill_validations', ['rule_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_freight_bill_validations_rule_name'), table_name='freight_bill_validations')
    op.drop_index(op.f('ix_freight_bill_validations_freight_bill_id'), table_name='freight_bill_validations')
    op.drop_table('freight_bill_validations')
    # ### end Alembic commands ###
