"""create initial logistics tables

Revision ID: 9386c6fa9b1f
Revises: 
Create Date: 2026-04-23 11:59:07.957243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9386c6fa9b1f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carriers',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('carrier_code', sa.String(length=50), nullable=False),
    sa.Column('gstin', sa.String(length=50), nullable=False),
    sa.Column('bank_account', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('onboarded_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrier_code'),
    sa.UniqueConstraint('gstin')
    )
    op.create_index(op.f('ix_carriers_name'), 'carriers', ['name'], unique=False)
    op.create_table('carrier_contracts',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('carrier_id', sa.String(length=50), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrier_contracts_carrier_id'), 'carrier_contracts', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_carrier_contracts_effective_date'), 'carrier_contracts', ['effective_date'], unique=False)
    op.create_index(op.f('ix_carrier_contracts_expiry_date'), 'carrier_contracts', ['expiry_date'], unique=False)
    op.create_table('freight_bills',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('carrier_id', sa.String(length=50), nullable=True),
    sa.Column('carrier_name_raw', sa.String(length=255), nullable=False),
    sa.Column('bill_number', sa.String(length=100), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('shipment_reference', sa.String(length=100), nullable=True),
    sa.Column('lane', sa.String(length=50), nullable=False),
    sa.Column('billed_weight_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rate_per_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('billing_unit', sa.String(length=20), nullable=True),
    sa.Column('base_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fuel_surcharge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('current_decision', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_bills_bill_date'), 'freight_bills', ['bill_date'], unique=False)
    op.create_index('ix_freight_bills_bill_number_carrier_id', 'freight_bills', ['bill_number', 'carrier_id'], unique=False)
    op.create_index(op.f('ix_freight_bills_carrier_id'), 'freight_bills', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_freight_bills_carrier_name_raw'), 'freight_bills', ['carrier_name_raw'], unique=False)
    op.create_index(op.f('ix_freight_bills_lane'), 'freight_bills', ['lane'], unique=False)
    op.create_index(op.f('ix_freight_bills_shipment_reference'), 'freight_bills', ['shipment_reference'], unique=False)
    op.create_table('contract_rate_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.String(length=100), nullable=False),
    sa.Column('lane_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rate_per_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_charge', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fuel_surcharge_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rate_per_unit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_capacity_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('alternate_rate_per_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('revised_on', sa.Date(), nullable=True),
    sa.Column('revised_fuel_surcharge_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['carrier_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_rate_cards_contract_id'), 'contract_rate_cards', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_rate_cards_lane_code'), 'contract_rate_cards', ['lane_code'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('carrier_id', sa.String(length=50), nullable=False),
    sa.Column('contract_id', sa.String(length=100), nullable=False),
    sa.Column('lane', sa.String(length=50), nullable=False),
    sa.Column('shipment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_weight_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['carrier_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_carrier_id'), 'shipments', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_shipments_contract_id'), 'shipments', ['contract_id'], unique=False)
    op.create_index(op.f('ix_shipments_lane'), 'shipments', ['lane'], unique=False)
    op.create_index(op.f('ix_shipments_shipment_date'), 'shipments', ['shipment_date'], unique=False)
    op.create_table('bills_of_lading',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('shipment_id', sa.String(length=100), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('actual_weight_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_of_lading_delivery_date'), 'bills_of_lading', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_bills_of_lading_shipment_id'), 'bills_of_lading', ['shipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bills_of_lading_shipment_id'), table_name='bills_of_lading')
    op.drop_index(op.f('ix_bills_of_lading_delivery_date'), table_name='bills_of_lading')
    op.drop_table('bills_of_lading')
    op.drop_index(op.f('ix_shipments_shipment_date'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_lane'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_contract_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_carrier_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_contract_rate_cards_lane_code'), table_name='contract_rate_cards')
    op.drop_index(op.f('ix_contract_rate_cards_contract_id'), table_name='contract_rate_cards')
    op.drop_table('contract_rate_cards')
    op.drop_index(op.f('ix_freight_bills_shipment_reference'), table_name='freight_bills')
    op.drop_index(op.f('ix_freight_bills_lane'), table_name='freight_bills')
    op.drop_index(op.f('ix_freight_bills_carrier_name_raw'), table_name='freight_bills')
    op.drop_index(op.f('ix_freight_bills_carrier_id'), table_name='freight_bills')
    op.drop_index('ix_freight_bills_bill_number_carrier_id', table_name='freight_bills')
    op.drop_index(op.f('ix_freight_bills_bill_date'), table_name='freight_bills')
    op.drop_table('freight_bills')
    op.drop_index(op.f('ix_carrier_contracts_expiry_date'), table_name='carrier_contracts')
    op.drop_index(op.f('ix_carrier_contracts_effective_date'), table_name='carrier_contracts')
    op.drop_index(op.f('ix_carrier_contracts_carrier_id'), table_name='carrier_contracts')
    op.drop_table('carrier_contracts')
    op.drop_index(op.f('ix_carriers_name'), table_name='carriers')
    op.drop_table('carriers')
    # ### end Alembic commands ###
