"""add selection and final resolution fields to freight bills

Revision ID: b7b20eba6360
Revises: 855bfd97d9b3
Create Date: 2026-04-23 18:12:30.486830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7b20eba6360'
down_revision: Union[str, None] = '855bfd97d9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freight_bills', sa.Column('selected_contract_id', sa.String(length=100), nullable=True))
    op.add_column('freight_bills', sa.Column('selected_shipment_id', sa.String(length=100), nullable=True))
    op.add_column('freight_bills', sa.Column('selected_bol_id', sa.String(length=100), nullable=True))
    op.add_column('freight_bills', sa.Column('final_resolution', sa.String(length=50), nullable=True))
    op.add_column('freight_bills', sa.Column('finalized_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_freight_bills_final_resolution'), 'freight_bills', ['final_resolution'], unique=False)
    op.create_index(op.f('ix_freight_bills_selected_bol_id'), 'freight_bills', ['selected_bol_id'], unique=False)
    op.create_index(op.f('ix_freight_bills_selected_contract_id'), 'freight_bills', ['selected_contract_id'], unique=False)
    op.create_index(op.f('ix_freight_bills_selected_shipment_id'), 'freight_bills', ['selected_shipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_freight_bills_selected_shipment_id'), table_name='freight_bills')
    op.drop_index(op.f('ix_freight_bills_selected_contract_id'), table_name='freight_bills')
    op.drop_index(op.f('ix_freight_bills_selected_bol_id'), table_name='freight_bills')
    op.drop_index(op.f('ix_freight_bills_final_resolution'), table_name='freight_bills')
    op.drop_column('freight_bills', 'finalized_at')
    op.drop_column('freight_bills', 'final_resolution')
    op.drop_column('freight_bills', 'selected_bol_id')
    op.drop_column('freight_bills', 'selected_shipment_id')
    op.drop_column('freight_bills', 'selected_contract_id')
    # ### end Alembic commands ###
